baseurl = "https://smbcantos.github.io/"
title = "ShellaCantos"

theme = "hugo-moss-theme"

languagecode = "en"
defaultcontentlanguage = "en"

paginate = 20
canonifyurls = true

pygmentsstyle = "b2"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

disqusShortname = "yourdiscussshortname"

[params]
    author = "Shella Cantos"
    description = "Shella's personal website"
    keywords = "blog,developer,personal"
    info = "Server Side Magician"
    footercontent = "Never a dead end."

    dateformat = "January 2, 2006"

    hideFooter = false
    hideCredits = true
    hideCopyright = false
    
    # Git Commit in Footer, uncomment the line below to enable it.
    #commit = "https://github.com/luizdepra/hugo-coder/tree/"

    rtl = false
    colorscheme = "light"

    # Series see also post count
    maxSeeAlsoItems = 5

    # Custom CSS
    custom_css = []

    # Custom JS
    custom_js = []

# If you want to use fathom(https://usefathom.com) for analytics, add this section
#[params.fathomAnalytics]
    #siteID = "ABCDE"
    # Default value is cdn.usefathom.com, overwrite this if you are self-hosting
    #serverURL = "analytics.example.com"

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"

[[params.social]]
    name = "Github"
    icon = "fab fa-github fa-2x"
    weight = 1
    url = "https://github.com/SmbCantos"
[[params.social]]
    name = "linkedin"
    icon = "fab fa-linkedin fa-2x"
    weight = 2
    url = "https://www.linkedin.com/in/shella-cantos-3bb124139/"
#[[params.social]]
#    name = "RSS"
#    icon = "fas fa-rss"
#    weight = 6
#    url = "https://myhugosite.com/index.xml"
#    rel = "alternate"
#    type = "application/rss+xml"

[[menu.main]]
    name = "About"
    weight = 1
    url = "about/"

[[menu.main]]
    name = "Blog"
    weight = 2
    url = "posts/"

[[menu.main]]
    name = "Categories"
    weight = 3
    url = "categories/"

[[menu.main]]
    name = "Contact me"
    weight = 4
    url = "contact/"
